dist: bionic
language: go
go:
  - '1.15'
git:
  depth: 1

jobs:
  include:
   - arch: arm64

script:
  # install bazel
  - npm install -g @bazel/bazelisk
  - bazelisk
  # install kind
  - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.9.0/kind-linux-arm64
  - chmod +x ./kind
  - sudo cp ./kind /usr/bin
  # checkout k8s
  - mkdir -p $GOPATH/src/k8s.io/kubernetes
  - git clone https://github.com/tcnghia/kubernetes --branch use-arm64-rules-docker $GOPATH/src/k8s.io/kubernetes
  - pushd $GOPATH/src/k8s.io/kubernetes
  - ./hack/print-workspace-status.sh
  - kind build node-image --type bazel
  # Show node images
  - docker images

notifications:
  email: false
